# Generated by Django 5.1.1 on 2024-09-18 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=100)),
                ('neiborhood', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
                ('rg_image', models.ImageField(upload_to='doctors/rgs')),
                ('medical_identity', models.ImageField(upload_to='doctors/medical_identity')),
                ('profile_image', models.ImageField(upload_to='doctors/profiles')),
                ('description', models.TextField()),
                ('consultation_price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
